/**
 * Auto-generated TypeScript types with @pinta365/openapi-typegen
 * Generated at: 2026-02-06T16:46:28.887Z
 * Source file: https://developers.strava.com/swagger/swagger.json
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * A set of rolled-up statistics and totals for an athlete
 *
 * Used by:
 *  - GET /athletes/{id}/stats
 */
export interface ActivityStats {
    /**
     * The longest distance ridden by the athlete.
     *
     * Format: double
     */
    biggestRideDistance?: number;
    /**
     * The highest climb ridden by the athlete.
     *
     * Format: double
     */
    biggestClimbElevationGain?: number;
    /** The recent (last 4 weeks) ride stats for the athlete. */
    recentRideTotals?: ActivityTotal;
    /** The recent (last 4 weeks) run stats for the athlete. */
    recentRunTotals?: ActivityTotal;
    /** The recent (last 4 weeks) swim stats for the athlete. */
    recentSwimTotals?: ActivityTotal;
    /** The year to date ride stats for the athlete. */
    ytdRideTotals?: ActivityTotal;
    /** The year to date run stats for the athlete. */
    ytdRunTotals?: ActivityTotal;
    /** The year to date swim stats for the athlete. */
    ytdSwimTotals?: ActivityTotal;
    /** The all time ride stats for the athlete. */
    allRideTotals?: ActivityTotal;
    /** The all time run stats for the athlete. */
    allRunTotals?: ActivityTotal;
    /** The all time swim stats for the athlete. */
    allSwimTotals?: ActivityTotal;
}

/**
 * Encapsulates the errors that may be returned from the API.
 *
 * Used by:
 *  - GET /athletes/{id}/stats
 *  - GET /athlete
 *  - PUT /athlete
 *  - GET /athlete/zones
 *  - GET /segments/{id}
 *  - GET /segments/starred
 *  - PUT /segments/{id}/starred
 *  - GET /segment_efforts
 *  - GET /segments/explore
 *  - GET /segment_efforts/{id}
 *  - POST /activities
 *  - GET /activities/{id}
 *  - PUT /activities/{id}
 *  - GET /athlete/activities
 *  - GET /activities/{id}/laps
 *  - GET /activities/{id}/zones
 *  - GET /activities/{id}/comments
 *  - GET /activities/{id}/kudos
 *  - GET /clubs/{id}
 *  - GET /clubs/{id}/members
 *  - GET /clubs/{id}/admins
 *  - GET /clubs/{id}/activities
 *  - GET /athlete/clubs
 *  - GET /gear/{id}
 *  - GET /routes/{id}
 *  - GET /athletes/{id}/routes
 *  - GET /routes/{id}/export_gpx
 *  - GET /routes/{id}/export_tcx
 *  - POST /uploads
 *  - GET /uploads/{uploadId}
 *  - GET /activities/{id}/streams
 *  - GET /segment_efforts/{id}/streams
 *  - GET /segments/{id}/streams
 *  - GET /routes/{id}/streams
 */
export interface Fault {
    /** The set of specific errors associated with this fault, if any. */
    errors?: Error[];
    /** The message of the fault. */
    message?: string;
}

/** Error */
export interface Error {
    /** The code associated with this error. */
    code?: string;
    /** The specific field or aspect of the resource associated with this error. */
    field?: string;
    /** The type of resource associated with this error. */
    resource?: string;
}

/**
 * DetailedAthlete
 *
 * Used by:
 *  - GET /athlete
 *  - PUT /athlete
 */
export interface DetailedAthlete extends SummaryAthlete {
    /** The athlete's follower count. */
    followerCount?: number;
    /** The athlete's friend count. */
    friendCount?: number;
    /** The athlete's preferred unit system. */
    measurementPreference?: "feet" | "meters";
    /** The athlete's FTP (Functional Threshold Power). */
    ftp?: number;
    /**
     * The athlete's weight.
     *
     * Format: float
     */
    weight?: number;
    /** The athlete's clubs. */
    clubs?: SummaryClub[];
    /** The athlete's bikes. */
    bikes?: SummaryGear[];
    /** The athlete's shoes. */
    shoes?: SummaryGear[];
}

/**
 * SummaryAthlete
 *
 * Used by:
 *  - GET /activities/{id}/kudos
 *  - GET /clubs/{id}/admins
 */
export interface SummaryAthlete extends MetaAthlete {
    /** Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail" */
    resourceState?: number;
    /** The athlete's first name. */
    firstname?: string;
    /** The athlete's last name. */
    lastname?: string;
    /** URL to a 62x62 pixel profile picture. */
    profileMedium?: string;
    /** URL to a 124x124 pixel profile picture. */
    profile?: string;
    /** The athlete's city. */
    city?: string;
    /** The athlete's state or geographical region. */
    state?: string;
    /** The athlete's country. */
    country?: string;
    /** The athlete's sex. */
    sex?: "M" | "F";
    /** Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription. */
    premium?: boolean;
    /** Whether the athlete has any Summit subscription. */
    summit?: boolean;
    /**
     * The time at which the athlete was created.
     *
     * Format: date-time
     */
    createdAt?: string;
    /**
     * The time at which the athlete was last updated.
     *
     * Format: date-time
     */
    updatedAt?: string;
}

/**
 * ClubAthlete
 *
 * Used by:
 *  - GET /clubs/{id}/members
 */
export interface ClubAthlete {
    /** Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail" */
    resourceState?: number;
    /** The athlete's first name. */
    firstname?: string;
    /** The athlete's last initial. */
    lastname?: string;
    /** The athlete's member status. */
    member?: string;
    /** Whether the athlete is a club admin. */
    admin?: boolean;
    /** Whether the athlete is club owner. */
    owner?: boolean;
}

/** MetaAthlete */
export interface MetaAthlete {
    /**
     * The unique identifier of the athlete
     *
     * Format: int64
     */
    id?: number;
}

/**
 * Zones
 *
 * Used by:
 *  - GET /athlete/zones
 */
export interface Zones {
    /** HeartRateZoneRanges */
    heartRate?: HeartRateZoneRanges;
    /** PowerZoneRanges */
    power?: PowerZoneRanges;
}

/** HeartRateZoneRanges */
export interface HeartRateZoneRanges {
    /** Whether the athlete has set their own custom heart rate zones */
    customZones?: boolean;
    /** ZoneRanges */
    zones?: ZoneRanges;
}

/** PowerZoneRanges */
export interface PowerZoneRanges {
    /** ZoneRanges */
    zones?: ZoneRanges;
}

/** ZoneRanges */
export type ZoneRanges = ZoneRange[];

/** ZoneRange */
export interface ZoneRange {
    /** The minimum value in the range. */
    min?: number;
    /** The maximum value in the range. */
    max?: number;
}

/** A union type representing the time spent in a given zone. */
export interface TimedZoneRange extends ZoneRange {
    /** The number of seconds spent in this zone */
    time?: number;
}

/** Stores the exclusive ranges representing zones and the time spent in each. */
export type TimedZoneDistribution = TimedZoneRange[];

/**
 * ActivityZone
 *
 * Used by:
 *  - GET /activities/{id}/zones
 */
export interface ActivityZone {
    score?: number;
    /** Stores the exclusive ranges representing zones and the time spent in each. */
    distributionBuckets?: TimedZoneDistribution;
    type?: "heartrate" | "power";
    sensorBased?: boolean;
    points?: number;
    customZones?: boolean;
    max?: number;
}

/**
 * DetailedSegment
 *
 * Used by:
 *  - GET /segments/{id}
 *  - PUT /segments/{id}/starred
 */
export interface DetailedSegment extends SummarySegment {
    /**
     * The time at which the segment was created.
     *
     * Format: date-time
     */
    createdAt?: string;
    /**
     * The time at which the segment was last updated.
     *
     * Format: date-time
     */
    updatedAt?: string;
    /**
     * The segment's total elevation gain.
     *
     * Format: float
     */
    totalElevationGain?: number;
    /** PolylineMap */
    map?: PolylineMap;
    /** The total number of efforts for this segment */
    effortCount?: number;
    /** The number of unique athletes who have an effort for this segment */
    athleteCount?: number;
    /** Whether this segment is considered hazardous */
    hazardous?: boolean;
    /** The number of stars for this segment */
    starCount?: number;
}

/**
 * SummarySegment
 *
 * Used by:
 *  - GET /segments/starred
 */
export interface SummarySegment {
    /**
     * The unique identifier of this segment
     *
     * Format: int64
     */
    id?: number;
    /** The name of this segment */
    name?: string;
    activityType?: "Ride" | "Run";
    /**
     * The segment's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /**
     * The segment's average grade, in percents
     *
     * Format: float
     */
    averageGrade?: number;
    /**
     * The segments's maximum grade, in percents
     *
     * Format: float
     */
    maximumGrade?: number;
    /**
     * The segments's highest elevation, in meters
     *
     * Format: float
     */
    elevationHigh?: number;
    /**
     * The segments's lowest elevation, in meters
     *
     * Format: float
     */
    elevationLow?: number;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    startLatlng?: LatLng;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    endLatlng?: LatLng;
    /** The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. */
    climbCategory?: number;
    /** The segments's city. */
    city?: string;
    /** The segments's state or geographical region. */
    state?: string;
    /** The segment's country. */
    country?: string;
    /** Whether this segment is private. */
    private?: boolean;
    /** SummaryPRSegmentEffort */
    athletePrEffort?: SummaryPRSegmentEffort;
    /** SummarySegmentEffort */
    athleteSegmentStats?: SummarySegmentEffort;
}

/**
 * ExplorerResponse
 *
 * Used by:
 *  - GET /segments/explore
 */
export interface ExplorerResponse {
    /** The set of segments matching an explorer request */
    segments?: ExplorerSegment[];
}

/** ExplorerSegment */
export interface ExplorerSegment {
    /**
     * The unique identifier of this segment
     *
     * Format: int64
     */
    id?: number;
    /** The name of this segment */
    name?: string;
    /** The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. If climb_category = 5, climb_category_desc = HC. If climb_category = 2, climb_category_desc = 3. */
    climbCategory?: number;
    /** The description for the category of the climb */
    climbCategoryDesc?: "NC" | "4" | "3" | "2" | "1" | "HC";
    /**
     * The segment's average grade, in percents
     *
     * Format: float
     */
    avgGrade?: number;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    startLatlng?: LatLng;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    endLatlng?: LatLng;
    /**
     * The segments's evelation difference, in meters
     *
     * Format: float
     */
    elevDifference?: number;
    /**
     * The segment's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /** The polyline of the segment */
    points?: string;
}

/**
 * DetailedSegmentEffort
 *
 * Used by:
 *  - GET /segment_efforts
 *  - GET /segment_efforts/{id}
 */
export interface DetailedSegmentEffort extends SummarySegmentEffort {
    /** The name of the segment on which this effort was performed */
    name?: string;
    /** MetaActivity */
    activity?: MetaActivity;
    /** MetaAthlete */
    athlete?: MetaAthlete;
    /** The effort's moving time */
    movingTime?: number;
    /** The start index of this effort in its activity's stream */
    startIndex?: number;
    /** The end index of this effort in its activity's stream */
    endIndex?: number;
    /**
     * The effort's average cadence
     *
     * Format: float
     */
    averageCadence?: number;
    /**
     * The average wattage of this effort
     *
     * Format: float
     */
    averageWatts?: number;
    /** For riding efforts, whether the wattage was reported by a dedicated recording device */
    deviceWatts?: boolean;
    /**
     * The heart heart rate of the athlete during this effort
     *
     * Format: float
     */
    averageHeartrate?: number;
    /**
     * The maximum heart rate of the athlete during this effort
     *
     * Format: float
     */
    maxHeartrate?: number;
    /** SummarySegment */
    segment?: SummarySegment;
    /** The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload */
    komRank?: number;
    /** The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload */
    prRank?: number;
    /** Whether this effort should be hidden when viewed within an activity */
    hidden?: boolean;
}

/** SummarySegmentEffort */
export interface SummarySegmentEffort {
    /**
     * The unique identifier of this effort
     *
     * Format: int64
     */
    id?: number;
    /**
     * The unique identifier of the activity related to this effort
     *
     * Format: int64
     */
    activityId?: number;
    /** The effort's elapsed time */
    elapsedTime?: number;
    /**
     * The time at which the effort was started.
     *
     * Format: date-time
     */
    startDate?: string;
    /**
     * The time at which the effort was started in the local timezone.
     *
     * Format: date-time
     */
    startDateLocal?: string;
    /**
     * The effort's distance in meters
     *
     * Format: float
     */
    distance?: number;
    /** Whether this effort is the current best on the leaderboard */
    isKom?: boolean;
}

/** SummaryPRSegmentEffort */
export interface SummaryPRSegmentEffort {
    /**
     * The unique identifier of the activity related to the PR effort.
     *
     * Format: int64
     */
    prActivityId?: number;
    /** The elapsed time ot the PR effort. */
    prElapsedTime?: number;
    /**
     * The time at which the PR effort was started.
     *
     * Format: date-time
     */
    prDate?: string;
    /** Number of efforts by the authenticated athlete on this segment. */
    effortCount?: number;
}

/**
 * DetailedActivity
 *
 * Used by:
 *  - POST /activities
 *  - GET /activities/{id}
 *  - PUT /activities/{id}
 */
export interface DetailedActivity extends SummaryActivity {
    /** The description of the activity */
    description?: string;
    /** PhotosSummary */
    photos?: PhotosSummary;
    /** SummaryGear */
    gear?: SummaryGear;
    /**
     * The number of kilocalories consumed during this activity
     *
     * Format: float
     */
    calories?: number;
    segmentEfforts?: DetailedSegmentEffort[];
    /** The name of the device used to record the activity */
    deviceName?: string;
    /** The token used to embed a Strava activity */
    embedToken?: string;
    /** The splits of this activity in metric units (for runs) */
    splitsMetric?: Split[];
    /** The splits of this activity in imperial units (for runs) */
    splitsStandard?: Split[];
    laps?: Lap[];
    bestEfforts?: DetailedSegmentEffort[];
}

/**
 * SummaryActivity
 *
 * Used by:
 *  - GET /athlete/activities
 */
export interface SummaryActivity extends MetaActivity {
    /** The identifier provided at upload time */
    externalId?: string;
    /**
     * The identifier of the upload that resulted in this activity
     *
     * Format: int64
     */
    uploadId?: number;
    /** MetaAthlete */
    athlete?: MetaAthlete;
    /** The name of the activity */
    name?: string;
    /**
     * The activity's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /** The activity's moving time, in seconds */
    movingTime?: number;
    /** The activity's elapsed time, in seconds */
    elapsedTime?: number;
    /**
     * The activity's total elevation gain.
     *
     * Format: float
     */
    totalElevationGain?: number;
    /**
     * The activity's highest elevation, in meters
     *
     * Format: float
     */
    elevHigh?: number;
    /**
     * The activity's lowest elevation, in meters
     *
     * Format: float
     */
    elevLow?: number;
    /** Deprecated. Prefer to use sport_type */
    type?: ActivityType;
    /** An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide) */
    sportType?: SportType;
    /**
     * The time at which the activity was started.
     *
     * Format: date-time
     */
    startDate?: string;
    /**
     * The time at which the activity was started in the local timezone.
     *
     * Format: date-time
     */
    startDateLocal?: string;
    /** The timezone of the activity */
    timezone?: string;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    startLatlng?: LatLng;
    /** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
    endLatlng?: LatLng;
    /** The number of achievements gained during this activity */
    achievementCount?: number;
    /** The number of kudos given for this activity */
    kudosCount?: number;
    /** The number of comments for this activity */
    commentCount?: number;
    /** The number of athletes for taking part in a group activity */
    athleteCount?: number;
    /** The number of Instagram photos for this activity */
    photoCount?: number;
    /** The number of Instagram and Strava photos for this activity */
    totalPhotoCount?: number;
    /** PolylineMap */
    map?: PolylineMap;
    /** The name of the device used to record the activity */
    deviceName?: string;
    /** Whether this activity was recorded on a training machine */
    trainer?: boolean;
    /** Whether this activity is a commute */
    commute?: boolean;
    /** Whether this activity was created manually */
    manual?: boolean;
    /** Whether this activity is private */
    private?: boolean;
    /** Whether this activity is flagged */
    flagged?: boolean;
    /** The activity's workout type */
    workoutType?: number;
    /** The unique identifier of the upload in string format */
    uploadIdStr?: string;
    /**
     * The activity's average speed, in meters per second
     *
     * Format: float
     */
    averageSpeed?: number;
    /**
     * The activity's max speed, in meters per second
     *
     * Format: float
     */
    maxSpeed?: number;
    /** Whether the logged-in athlete has kudoed this activity */
    hasKudoed?: boolean;
    /** Whether the activity is muted */
    hideFromHome?: boolean;
    /** The id of the gear for the activity */
    gearId?: string;
    /**
     * The total work done in kilojoules during this activity. Rides only
     *
     * Format: float
     */
    kilojoules?: number;
    /**
     * Average power output in watts during this activity. Rides only
     *
     * Format: float
     */
    averageWatts?: number;
    /** Whether the watts are from a power meter, false if estimated */
    deviceWatts?: boolean;
    /** Rides with power meter data only */
    maxWatts?: number;
    /** Similar to Normalized Power. Rides with power meter data only */
    weightedAverageWatts?: number;
}

/** MetaActivity */
export interface MetaActivity {
    /**
     * The unique identifier of the activity
     *
     * Format: int64
     */
    id?: number;
}

/**
 * UpdatableActivity
 *
 * Used by:
 *  - PUT /activities/{id}
 */
export interface UpdatableActivity {
    /** Whether this activity is a commute */
    commute?: boolean;
    /** Whether this activity was recorded on a training machine */
    trainer?: boolean;
    /** Whether this activity is muted */
    hideFromHome?: boolean;
    /** The description of the activity */
    description?: string;
    /** The name of the activity */
    name?: string;
    /** Deprecated. Prefer to use sport_type. In a request where both type and sport_type are present, this field will be ignored */
    type?: ActivityType;
    /** An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide) */
    sportType?: SportType;
    /** Identifier for the gear associated with the activity. ‘none’ clears gear from activity */
    gearId?: string;
}

/**
 * ClubActivity
 *
 * Used by:
 *  - GET /clubs/{id}/activities
 */
export interface ClubActivity {
    /** MetaAthlete */
    athlete?: MetaAthlete;
    /** The name of the activity */
    name?: string;
    /**
     * The activity's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /** The activity's moving time, in seconds */
    movingTime?: number;
    /** The activity's elapsed time, in seconds */
    elapsedTime?: number;
    /**
     * The activity's total elevation gain.
     *
     * Format: float
     */
    totalElevationGain?: number;
    /** Deprecated. Prefer to use sport_type */
    type?: ActivityType;
    /** An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide) */
    sportType?: SportType;
    /** The activity's workout type */
    workoutType?: number;
}

/**
 * Lap
 *
 * Used by:
 *  - GET /activities/{id}/laps
 */
export interface Lap {
    /**
     * The unique identifier of this lap
     *
     * Format: int64
     */
    id?: number;
    /** MetaActivity */
    activity?: MetaActivity;
    /** MetaAthlete */
    athlete?: MetaAthlete;
    /**
     * The lap's average cadence
     *
     * Format: float
     */
    averageCadence?: number;
    /**
     * The lap's average speed
     *
     * Format: float
     */
    averageSpeed?: number;
    /**
     * The lap's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /** The lap's elapsed time, in seconds */
    elapsedTime?: number;
    /** The start index of this effort in its activity's stream */
    startIndex?: number;
    /** The end index of this effort in its activity's stream */
    endIndex?: number;
    /** The index of this lap in the activity it belongs to */
    lapIndex?: number;
    /**
     * The maximum speed of this lat, in meters per second
     *
     * Format: float
     */
    maxSpeed?: number;
    /** The lap's moving time, in seconds */
    movingTime?: number;
    /** The name of the lap */
    name?: string;
    /** The athlete's pace zone during this lap */
    paceZone?: number;
    split?: number;
    /**
     * The time at which the lap was started.
     *
     * Format: date-time
     */
    startDate?: string;
    /**
     * The time at which the lap was started in the local timezone.
     *
     * Format: date-time
     */
    startDateLocal?: string;
    /**
     * The elevation gain of this lap, in meters
     *
     * Format: float
     */
    totalElevationGain?: number;
}

/**
 * Comment
 *
 * Used by:
 *  - GET /activities/{id}/comments
 */
export interface Comment {
    /**
     * The unique identifier of this comment
     *
     * Format: int64
     */
    id?: number;
    /**
     * The identifier of the activity this comment is related to
     *
     * Format: int64
     */
    activityId?: number;
    /** The content of the comment */
    text?: string;
    /** SummaryAthlete */
    athlete?: SummaryAthlete;
    /**
     * The time at which this comment was created.
     *
     * Format: date-time
     */
    createdAt?: string;
}

/**
 * DetailedClub
 *
 * Used by:
 *  - GET /clubs/{id}
 */
export interface DetailedClub extends SummaryClub {
    /** The membership status of the logged-in athlete. */
    membership?: "member" | "pending";
    /** Whether the currently logged-in athlete is an administrator of this club. */
    admin?: boolean;
    /** Whether the currently logged-in athlete is the owner of this club. */
    owner?: boolean;
    /** The number of athletes in the club that the logged-in athlete follows. */
    followingCount?: number;
}

/**
 * SummaryClub
 *
 * Used by:
 *  - GET /athlete/clubs
 */
export interface SummaryClub extends MetaClub {
    /** URL to a 60x60 pixel profile picture. */
    profileMedium?: string;
    /** URL to a ~1185x580 pixel cover photo. */
    coverPhoto?: string;
    /** URL to a ~360x176  pixel cover photo. */
    coverPhotoSmall?: string;
    /** Deprecated. Prefer to use activity_types. */
    sportType?: "cycling" | "running" | "triathlon" | "other";
    /** The activity types that count for a club. This takes precedence over sport_type. */
    activityTypes?: ActivityType[];
    /** The club's city. */
    city?: string;
    /** The club's state or geographical region. */
    state?: string;
    /** The club's country. */
    country?: string;
    /** Whether the club is private. */
    private?: boolean;
    /** The club's member count. */
    memberCount?: number;
    /** Whether the club is featured or not. */
    featured?: boolean;
    /** Whether the club is verified or not. */
    verified?: boolean;
    /** The club's vanity URL. */
    url?: string;
}

/** MetaClub */
export interface MetaClub {
    /**
     * The club's unique identifier.
     *
     * Format: int64
     */
    id?: number;
    /** Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail" */
    resourceState?: number;
    /** The club's name. */
    name?: string;
}

/** ClubAnnouncement */
export interface ClubAnnouncement {
    /**
     * The unique identifier of this announcement.
     *
     * Format: int64
     */
    id?: number;
    /**
     * The unique identifier of the club this announcements was made in.
     *
     * Format: int64
     */
    clubId?: number;
    /** SummaryAthlete */
    athlete?: SummaryAthlete;
    /**
     * The time at which this announcement was created.
     *
     * Format: date-time
     */
    createdAt?: string;
    /** The content of this announcement */
    message?: string;
}

/** MembershipApplication */
export interface MembershipApplication {
    /** Whether the application for membership was successfully submitted */
    success?: boolean;
    /** Whether the membership is currently active */
    active?: boolean;
    /** The membership status of this application */
    membership?: "member" | "pending";
}

/**
 * DetailedGear
 *
 * Used by:
 *  - GET /gear/{id}
 */
export interface DetailedGear extends SummaryGear {
    /** The gear's brand name. */
    brandName?: string;
    /** The gear's model name. */
    modelName?: string;
    /** The gear's frame type (bike only). */
    frameType?: number;
    /** The gear's description. */
    description?: string;
}

/** SummaryGear */
export interface SummaryGear {
    /** The gear's unique identifier. */
    id?: string;
    /** Resource state, indicates level of detail. Possible values: 2 -> "summary", 3 -> "detail" */
    resourceState?: number;
    /** Whether this gear's is the owner's default one. */
    primary?: boolean;
    /** The gear's name. */
    name?: string;
    /**
     * The distance logged with this gear.
     *
     * Format: float
     */
    distance?: number;
}

/**
 * Route
 *
 * Used by:
 *  - GET /routes/{id}
 *  - GET /athletes/{id}/routes
 */
export interface Route {
    /** SummaryAthlete */
    athlete?: SummaryAthlete;
    /** The description of the route */
    description?: string;
    /**
     * The route's distance, in meters
     *
     * Format: float
     */
    distance?: number;
    /**
     * The route's elevation gain.
     *
     * Format: float
     */
    elevationGain?: number;
    /**
     * The unique identifier of this route
     *
     * Format: int64
     */
    id?: number;
    /** The unique identifier of the route in string format */
    idStr?: string;
    /** PolylineMap */
    map?: PolylineMap;
    /** The name of this route */
    name?: string;
    /** Whether this route is private */
    private?: boolean;
    /** Whether this route is starred by the logged-in athlete */
    starred?: boolean;
    /** An epoch timestamp of when the route was created */
    timestamp?: number;
    /** This route's type (1 for ride, 2 for runs) */
    type?: number;
    /** This route's sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed) */
    subType?: number;
    /**
     * The time at which the route was created
     *
     * Format: date-time
     */
    createdAt?: string;
    /**
     * The time at which the route was last updated
     *
     * Format: date-time
     */
    updatedAt?: string;
    /** Estimated time in seconds for the authenticated athlete to complete route */
    estimatedMovingTime?: number;
    /** The segments traversed by this route */
    segments?: SummarySegment[];
    /** The custom waypoints along this route */
    waypoints?: Waypoint[];
}

/**
 * Upload
 *
 * Used by:
 *  - POST /uploads
 *  - GET /uploads/{uploadId}
 */
export interface Upload {
    /**
     * The unique identifier of the upload
     *
     * Format: int64
     */
    id?: number;
    /** The unique identifier of the upload in string format */
    idStr?: string;
    /** The external identifier of the upload */
    externalId?: string;
    /** The error associated with this upload */
    error?: string;
    /** The status of this upload */
    status?: string;
    /**
     * The identifier of the activity this upload resulted into
     *
     * Format: int64
     */
    activityId?: number;
}

/** An enumeration of the supported types of streams. */
export type StreamType =
    | "time"
    | "distance"
    | "latlng"
    | "altitude"
    | "velocity_smooth"
    | "heartrate"
    | "cadence"
    | "watts"
    | "temp"
    | "moving"
    | "grade_smooth";

/** BaseStream */
export interface BaseStream {
    /** The number of data points in this stream */
    originalSize?: number;
    /** The level of detail (sampling) in which this stream was returned */
    resolution?: "low" | "medium" | "high";
    /** The base series used in the case the stream was downsampled */
    seriesType?: "distance" | "time";
}

/** DistanceStream */
export interface DistanceStream extends BaseStream {
    /** The sequence of distance values for this stream, in meters */
    data?: number[];
}

/** TimeStream */
export interface TimeStream extends BaseStream {
    /** The sequence of time values for this stream, in seconds */
    data?: number[];
}

/** LatLngStream */
export interface LatLngStream extends BaseStream {
    /** The sequence of lat/long values for this stream */
    data?: LatLng[];
}

/** AltitudeStream */
export interface AltitudeStream extends BaseStream {
    /** The sequence of altitude values for this stream, in meters */
    data?: number[];
}

/** SmoothVelocityStream */
export interface SmoothVelocityStream extends BaseStream {
    /** The sequence of velocity values for this stream, in meters per second */
    data?: number[];
}

/** HeartrateStream */
export interface HeartrateStream extends BaseStream {
    /** The sequence of heart rate values for this stream, in beats per minute */
    data?: number[];
}

/** CadenceStream */
export interface CadenceStream extends BaseStream {
    /** The sequence of cadence values for this stream, in rotations per minute */
    data?: number[];
}

/** PowerStream */
export interface PowerStream extends BaseStream {
    /** The sequence of power values for this stream, in watts */
    data?: number[];
}

/** TemperatureStream */
export interface TemperatureStream extends BaseStream {
    /** The sequence of temperature values for this stream, in celsius degrees */
    data?: number[];
}

/** MovingStream */
export interface MovingStream extends BaseStream {
    /** The sequence of moving values for this stream, as boolean values */
    data?: boolean[];
}

/** SmoothGradeStream */
export interface SmoothGradeStream extends BaseStream {
    /** The sequence of grade values for this stream, as percents of a grade */
    data?: number[];
}

/**
 * StreamSet
 *
 * Used by:
 *  - GET /activities/{id}/streams
 *  - GET /segment_efforts/{id}/streams
 *  - GET /segments/{id}/streams
 *  - GET /routes/{id}/streams
 */
export interface StreamSet {
    /** TimeStream */
    time?: TimeStream;
    /** DistanceStream */
    distance?: DistanceStream;
    /** LatLngStream */
    latlng?: LatLngStream;
    /** AltitudeStream */
    altitude?: AltitudeStream;
    /** SmoothVelocityStream */
    velocitySmooth?: SmoothVelocityStream;
    /** HeartrateStream */
    heartrate?: HeartrateStream;
    /** CadenceStream */
    cadence?: CadenceStream;
    /** PowerStream */
    watts?: PowerStream;
    /** TemperatureStream */
    temp?: TemperatureStream;
    /** MovingStream */
    moving?: MovingStream;
    /** SmoothGradeStream */
    gradeSmooth?: SmoothGradeStream;
}

/** A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters. */
export interface ActivityTotal {
    /** The number of activities considered in this total. */
    count?: number;
    /**
     * The total distance covered by the considered activities.
     *
     * Format: float
     */
    distance?: number;
    /** The total moving time of the considered activities. */
    movingTime?: number;
    /** The total elapsed time of the considered activities. */
    elapsedTime?: number;
    /**
     * The total elevation gain of the considered activities.
     *
     * Format: float
     */
    elevationGain?: number;
    /** The total number of achievements of the considered activities. */
    achievementCount?: number;
}

/** PolylineMap */
export interface PolylineMap {
    /** The identifier of the map */
    id?: string;
    /** The polyline of the map, only returned on detailed representation of an object */
    polyline?: string;
    /** The summary polyline of the map */
    summaryPolyline?: string;
}

/** A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers. */
export type LatLng = number[];

/** PhotosSummary */
export interface PhotosSummary {
    /** The number of photos */
    count?: number;
    primary?: {
        /** Format: int64 */
        id?: number;
        source?: number;
        uniqueId?: string;
        urls?: object;
    };
}

/** Split */
export interface Split {
    /**
     * The average speed of this split, in meters per second
     *
     * Format: float
     */
    averageSpeed?: number;
    /**
     * The distance of this split, in meters
     *
     * Format: float
     */
    distance?: number;
    /** The elapsed time of this split, in seconds */
    elapsedTime?: number;
    /**
     * The elevation difference of this split, in meters
     *
     * Format: float
     */
    elevationDifference?: number;
    /** The pacing zone of this split */
    paceZone?: number;
    /** The moving time of this split, in seconds */
    movingTime?: number;
    /** N/A */
    split?: number;
}

/** An enumeration of the types an activity may have. Note that this enumeration does not include new sport types (e.g. MountainBikeRide, EMountainBikeRide), activities with these sport types will have the corresponding activity type (e.g. Ride for MountainBikeRide, EBikeRide for EMountainBikeRide) */
export type ActivityType =
    | "AlpineSki"
    | "BackcountrySki"
    | "Canoeing"
    | "Crossfit"
    | "EBikeRide"
    | "Elliptical"
    | "Golf"
    | "Handcycle"
    | "Hike"
    | "IceSkate"
    | "InlineSkate"
    | "Kayaking"
    | "Kitesurf"
    | "NordicSki"
    | "Ride"
    | "RockClimbing"
    | "RollerSki"
    | "Rowing"
    | "Run"
    | "Sail"
    | "Skateboard"
    | "Snowboard"
    | "Snowshoe"
    | "Soccer"
    | "StairStepper"
    | "StandUpPaddling"
    | "Surfing"
    | "Swim"
    | "Velomobile"
    | "VirtualRide"
    | "VirtualRun"
    | "Walk"
    | "WeightTraining"
    | "Wheelchair"
    | "Windsurf"
    | "Workout"
    | "Yoga";

/** An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide) */
export type SportType =
    | "AlpineSki"
    | "BackcountrySki"
    | "Badminton"
    | "Canoeing"
    | "Crossfit"
    | "EBikeRide"
    | "Elliptical"
    | "EMountainBikeRide"
    | "Golf"
    | "GravelRide"
    | "Handcycle"
    | "HighIntensityIntervalTraining"
    | "Hike"
    | "IceSkate"
    | "InlineSkate"
    | "Kayaking"
    | "Kitesurf"
    | "MountainBikeRide"
    | "NordicSki"
    | "Pickleball"
    | "Pilates"
    | "Racquetball"
    | "Ride"
    | "RockClimbing"
    | "RollerSki"
    | "Rowing"
    | "Run"
    | "Sail"
    | "Skateboard"
    | "Snowboard"
    | "Snowshoe"
    | "Soccer"
    | "Squash"
    | "StairStepper"
    | "StandUpPaddling"
    | "Surfing"
    | "Swim"
    | "TableTennis"
    | "Tennis"
    | "TrailRun"
    | "Velomobile"
    | "VirtualRide"
    | "VirtualRow"
    | "VirtualRun"
    | "Walk"
    | "WeightTraining"
    | "Wheelchair"
    | "Windsurf"
    | "Workout"
    | "Yoga";

/** Waypoint */
export interface Waypoint {
    /** The location along the route that the waypoint is closest to */
    latlng?: LatLng;
    /** A location off of the route that the waypoint is (optional) */
    targetLatlng?: LatLng;
    /** Categories that the waypoint belongs to */
    categories?: string[];
    /** A title for the waypoint */
    title?: string;
    /** A description of the waypoint (optional) */
    description?: string;
    /**
     * The number meters along the route that the waypoint is located
     *
     * Format: float
     */
    distanceIntoRoute?: number;
}
